/* This file is @generated by `ts-node scripts/build.ts`, DO NOT EDIT IT MANUALLY! */
/* prettier-ignore */
/* eslint-disable */
// ==UserScript==
// @name B 站网页端直播
// @namespace ProgramRipper
// @version 0.2.1
// @author ProgramRipper
// @license MIT
// @description 在 B 站网页端开播
// @homepage https://github.com/ProgramRipper/BLiveWeb
// @icon https://www.bilibili.com/favicon.ico
// @updateURL https://hub.hanbi.live/ProgramRipper/BLiveWeb/refs/heads/master/lib/index.user.js
// @downloadURL https://hub.hanbi.live/ProgramRipper/BLiveWeb/refs/heads/master/lib/index.user.js
// @supportURL https://github.com/ProgramRipper/BLiveWeb/issues
// @match *://link.bilibili.com/*
// @connect api.live.bilibili.com
// @connect *
// ==/UserScript==
(()=>{let n=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(i,t,r=!0,o=null,p=null){let{host:a,pathname:l}=new URL(t.startsWith("//")?"https:"+t:t);switch([i,a,l].toString()){case["GET","api.live.bilibili.com","/xlive/app-blink/v1/live/GetWebLivePermission"].toString():let c=Object.getOwnPropertyDescriptor(XMLHttpRequest.prototype,"responseText")?.get;Object.defineProperty(this,"responseText",{get(){let e=JSON.parse(c?.call(this));return e.data.allow_live=!0,JSON.stringify(e)}});break;case["POST","api.live.bilibili.com","/room/v1/Room/startLive"].toString():this.send=e=>{let s=new URLSearchParams(e);s.set("platform","pc_link"),XMLHttpRequest.prototype.send.call(this,s.toString())};break}n.call(this,i,t,r,o,p)}})();
