/* This file is @generated by `ts-node scripts/build.ts`, DO NOT EDIT IT MANUALLY! */
/* prettier-ignore */
/* eslint-disable */
// ==UserScript==
// @name B 站网页端直播
// @namespace ProgramRipper
// @version 0.2.1
// @author ProgramRipper
// @license MIT
// @description 在 B 站网页端开播
// @homepage https://github.com/ProgramRipper/BLiveWeb
// @icon https://www.bilibili.com/favicon.ico
// @updateURL https://hub.hanbi.live/ProgramRipper/BLiveWeb/refs/heads/master/lib/index.user.js
// @downloadURL https://hub.hanbi.live/ProgramRipper/BLiveWeb/refs/heads/master/lib/index.user.js
// @supportURL https://github.com/ProgramRipper/BLiveWeb/issues
// @match *://link.bilibili.com/*
// @connect api.live.bilibili.com
// @connect *
// ==/UserScript==
(()=>{let r=XMLHttpRequest.prototype.open;XMLHttpRequest.prototype.open=function(i,e,p=!0,a=null,l=null){let{host:n,pathname:o}=new URL(e.startsWith("//")?"https:"+e:e);switch(i){case"GET":if(n==="api.live.bilibili.com"&&o==="/xlive/app-blink/v1/live/GetWebLivePermission"){let s=Object.getOwnPropertyDescriptor(XMLHttpRequest.prototype,"responseText")?.get;Object.defineProperty(this,"responseText",{get(){let t=JSON.parse(s?.call(this));return t.data.allow_live=!0,JSON.stringify(t)}})}break;case"POST":n==="api.live.bilibili.com"&&o==="/room/v1/Room/startLive"&&(this.send=s=>{let t=new URLSearchParams(s);t.set("platform","ios"),XMLHttpRequest.prototype.send.call(this,t.toString())});break}r.call(this,i,e,p,a,l)}})();
