import esbuild from "esbuild";
import { readFileSync } from "fs";
import { resolve } from "path";

const packageJson = JSON.parse(
  readFileSync(resolve(__dirname, "../package.json"), "utf8"),
);

const downloadURL =
  "https://hub.hanbi.live/ProgramRipper/BLiveWeb/refs/heads/master/lib/index.user.js";

const banner = {
  name: packageJson.name.split("/")[1],
  namespace: packageJson.name.split("/")[0].slice(1),
  version: packageJson.version,
  author: packageJson.author.name,
  license: packageJson.license,
  description: packageJson.description,
  homepage: packageJson.homepage,
  icon: "https://www.bilibili.com/favicon.ico",
  updateURL: downloadURL,
  downloadURL: downloadURL,
  supportURL: packageJson.bugs,
  match: "*://link.bilibili.com/*",
  connect: ["api.live.bilibili.com", "*"],
  grant: "unsafeWindow",
  "run-at": "document-start",
} as Record<string, string | string[]>;
const bannerContent = Object.entries(banner)
  .map(([key, value]) =>
    (typeof value === "string" ? [value] : value)
      .map((v) => `// @${key} ${v}`)
      .join("\n"),
  )
  .join("\n");

esbuild.buildSync({
  entryPoints: [resolve(__dirname, "../src/index.user.ts")],
  outfile: resolve(__dirname, "../lib/index.user.js"),
  bundle: true,
  platform: "browser",
  format: "esm",
  minify: true,
  banner: {
    js: `\
/* This file is @generated by \`ts-node scripts/build.ts\`, DO NOT EDIT IT MANUALLY! */
/* prettier-ignore */
/* eslint-disable */
// ==UserScript==
${bannerContent}
// ==/UserScript==\
`,
  },
  legalComments: "none",
});
